### ISSUE TITLE
Hotkey for open in a new window

### ISSUE THREAD

**Issue by Archie-2021** [tadashi-aikawa/shukuchi#4]
Please add a new hotkey for open in a new window.

Thanks

**Comment by tadashi-aikawa** [comment]
Sorry for my late answer, @Archie-2021.

I want to give it a try 👍

**Comment by Archie-2021** [comment]
> Sorry for my late answer, @Archie-2021.
> 
> I want to give it a try 👍 

Np , Thanks, looking forward for it.

**Comment by tadashi-aikawa** [comment]
@Archie-2021 
Released in [v0.4.0](https://github.com/tadashi-aikawa/shukuchi/releases/tag/0.4.0) 🚀
